sudo: false
language: node_js
node_js:
  - '10'
rvm:
  -10.13.0
  -npm
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - cd client && npm test
  - npm run coveralls
